# Auto-generated reference data extracted from the original Excel workbook.

SEED_RECORDS = [
  {
    "id": "seed-0",
    "date": "2026-06-01",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_G33",
    "machineNo": "8",
    "deviceDetail": "Motor",
    "deviceSubCat": "m61",
    "faultCategory": "Motor",
    "reason": "Motor",
    "actionTaken": "replaced the motor and started the  machine",
    "shift": "C",
    "technician": "Afaq",
    "timeStart": "23:30",
    "timeFinish": "00:35",
    "downtime": "01:05",
    "remarks": ""
  },
  {
    "id": "seed-1",
    "date": "2026-06-02",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_G33",
    "machineNo": "8",
    "deviceDetail": "Coolant_Pipes",
    "deviceSubCat": "Coolant_Pipes",
    "faultCategory": "Coolant Leakage",
    "reason": "Coolant_Pipes",
    "actionTaken": "repair  the coolant pipes and started the machine",
    "shift": "A",
    "technician": "Makki Khan",
    "timeStart": "13:26",
    "timeFinish": "14:10",
    "downtime": "00:44",
    "remarks": ""
  },
  {
    "id": "seed-2",
    "date": "2026-06-02",
    "complaintReference": "Power House",
    "ticketNo": "",
    "machine": "Complete",
    "machineNo": "ALL",
    "deviceDetail": "",
    "deviceSubCat": "-",
    "faultCategory": "Shut Down",
    "reason": "Shut Down",
    "actionTaken": "after power restoration started the department",
    "shift": "B",
    "technician": "Makki Khan",
    "timeStart": "16:11",
    "timeFinish": "17:15",
    "downtime": "01:04",
    "remarks": ""
  },
  {
    "id": "seed-3",
    "date": "2026-06-02",
    "complaintReference": "Power House",
    "ticketNo": "",
    "machine": "Complete",
    "machineNo": "ALL",
    "deviceDetail": "",
    "deviceSubCat": "-",
    "faultCategory": "Shut Down",
    "reason": "Shut Down",
    "actionTaken": "after power restoration started the department",
    "shift": "B",
    "technician": "Afaq",
    "timeStart": "20:10",
    "timeFinish": "21:00",
    "downtime": "00:50",
    "remarks": ""
  },
  {
    "id": "seed-4",
    "date": "2026-06-02",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "AutoCone_21C",
    "machineNo": "2",
    "deviceDetail": "Motor",
    "deviceSubCat": "m6",
    "faultCategory": "CBF Conveyor",
    "reason": "Motor",
    "actionTaken": "checked and started the machine",
    "shift": "C",
    "technician": "M. Rauf",
    "timeStart": "23:15",
    "timeFinish": "23:40",
    "downtime": "00:25",
    "remarks": ""
  },
  {
    "id": "seed-5",
    "date": "2026-06-02",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Simplex",
    "machineNo": "4",
    "deviceDetail": "",
    "deviceSubCat": "-",
    "faultCategory": "Jack Loosing",
    "reason": "Jack Loosing",
    "actionTaken": "checked the jack loosing and started machine",
    "shift": "B+C",
    "technician": "M. Rauf",
    "timeStart": "18:15",
    "timeFinish": "19:15",
    "downtime": "01:00",
    "remarks": ""
  },
  {
    "id": "seed-6",
    "date": "2026-06-04",
    "complaintReference": "Power House",
    "ticketNo": "",
    "machine": "Complete",
    "machineNo": "ALL",
    "deviceDetail": "",
    "deviceSubCat": "-",
    "faultCategory": "Shut Down",
    "reason": "Shut Down",
    "actionTaken": "after power restoration started the department",
    "shift": "B",
    "technician": "Makki Khan",
    "timeStart": "15:10",
    "timeFinish": "16:20",
    "downtime": "01:10",
    "remarks": ""
  },
  {
    "id": "seed-7",
    "date": "2026-06-04",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_G33",
    "machineNo": "8",
    "deviceDetail": "Sensor",
    "deviceSubCat": "SQ23D",
    "faultCategory": "Sensor",
    "reason": "Wire Breakage",
    "actionTaken": "repair the wire and started the machine",
    "shift": "A",
    "technician": "Makki Khan",
    "timeStart": "08:15",
    "timeFinish": "08:25",
    "downtime": "00:10",
    "remarks": ""
  },
  {
    "id": "seed-8",
    "date": "2026-06-04",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Complete",
    "machineNo": "ALL",
    "deviceDetail": "Low Pressure",
    "deviceSubCat": "-",
    "faultCategory": "Low Pressure",
    "reason": "Low Pressure",
    "actionTaken": "after restoration of pressure department started",
    "shift": "A",
    "technician": "Makki Khan",
    "timeStart": "12:40",
    "timeFinish": "14:45",
    "downtime": "02:05",
    "remarks": ""
  },
  {
    "id": "seed-9",
    "date": "2026-06-05",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "A_11",
    "machineNo": "1",
    "deviceDetail": "Safety_Switch ",
    "deviceSubCat": "-",
    "faultCategory": "Safety Circuit",
    "reason": "Safety Circuit",
    "actionTaken": "checked  and started the machine",
    "shift": "A",
    "technician": "Makki Khan",
    "timeStart": "13:50",
    "timeFinish": "14:15",
    "downtime": "00:25",
    "remarks": ""
  },
  {
    "id": "seed-10",
    "date": "2026-06-05",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_G33",
    "machineNo": "7",
    "deviceDetail": "Motor",
    "deviceSubCat": "m81",
    "faultCategory": "Coolant Leakage",
    "reason": "Coolant Leakage",
    "actionTaken": "replaced the motor, U80 inverter and started the  machine",
    "shift": "B+C",
    "technician": "M. Rauf",
    "timeStart": "21:30",
    "timeFinish": "23:30",
    "downtime": "02:00",
    "remarks": ""
  },
  {
    "id": "seed-11",
    "date": "2026-06-06",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_K45",
    "machineNo": "5",
    "deviceDetail": "",
    "deviceSubCat": "Machine Washout",
    "faultCategory": "Machine Washout",
    "reason": "Machine Washout",
    "actionTaken": "checked motor and inverters and started the machine",
    "shift": "A",
    "technician": "M. Mazhar",
    "timeStart": "12:00",
    "timeFinish": "13:00",
    "downtime": "01:00",
    "remarks": ""
  },
  {
    "id": "seed-12",
    "date": "2026-06-06",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_G33",
    "machineNo": "7",
    "deviceDetail": "Pressure_Switch_Transducer",
    "deviceSubCat": "F113",
    "faultCategory": "Pressure_Switch_Transducer",
    "reason": "Wire Breakage",
    "actionTaken": "repair the wire and started the machine",
    "shift": "A",
    "technician": "M. Mazhar",
    "timeStart": "13:27",
    "timeFinish": "13:53",
    "downtime": "00:26",
    "remarks": ""
  },
  {
    "id": "seed-13",
    "date": "2026-06-06",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_K45",
    "machineNo": "4",
    "deviceDetail": "Inverter_VFD",
    "deviceSubCat": "U80",
    "faultCategory": "Inverter_VFD",
    "reason": "Inverter Fault",
    "actionTaken": "checked and took all the necessary measurement and started the machine",
    "shift": "C",
    "technician": "M. Rauf",
    "timeStart": "03:12",
    "timeFinish": "03:30",
    "downtime": "00:18",
    "remarks": ""
  },
  {
    "id": "seed-14",
    "date": "2026-06-07",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_G33",
    "machineNo": "9",
    "deviceDetail": "",
    "deviceSubCat": "-",
    "faultCategory": "Machine Washout",
    "reason": "Machine Washout",
    "actionTaken": "checked motors and inverters and started the machine",
    "shift": "A+B",
    "technician": "Makki Khan",
    "timeStart": "13:52",
    "timeFinish": "15:27",
    "downtime": "01:35",
    "remarks": ""
  },
  {
    "id": "seed-15",
    "date": "2026-06-07",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_G33",
    "machineNo": "9",
    "deviceDetail": "Inverter_VFD",
    "deviceSubCat": "U80",
    "faultCategory": "Inverter_VFD",
    "reason": "Inverter_VFD",
    "actionTaken": "replaced the inverter and started the machine",
    "shift": "C",
    "technician": "Afaq",
    "timeStart": "21:20",
    "timeFinish": "22:35",
    "downtime": "01:15",
    "remarks": ""
  },
  {
    "id": "seed-16",
    "date": "2026-06-08",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_G33",
    "machineNo": "8",
    "deviceDetail": "Sensor",
    "deviceSubCat": "B321",
    "faultCategory": "Sensor",
    "reason": "Setting Out",
    "actionTaken": "correct sensor setting through mechanical fitter and started the machine ",
    "shift": "A",
    "technician": "Makki Khan",
    "timeStart": "12:20",
    "timeFinish": "12:40",
    "downtime": "00:20",
    "remarks": ""
  },
  {
    "id": "seed-17",
    "date": "2026-06-08",
    "complaintReference": "Power House",
    "ticketNo": "",
    "machine": "Complete",
    "machineNo": "ALL",
    "deviceDetail": "",
    "deviceSubCat": "-",
    "faultCategory": "Shut Down",
    "reason": "Shut Down",
    "actionTaken": "after power restoration started the department",
    "shift": "B",
    "technician": "M. Mazhar",
    "timeStart": "15:58",
    "timeFinish": "16:28",
    "downtime": "00:30",
    "remarks": ""
  },
  {
    "id": "seed-18",
    "date": "2026-06-09",
    "complaintReference": "Power House",
    "ticketNo": "",
    "machine": "Complete",
    "machineNo": "ALL",
    "deviceDetail": "",
    "deviceSubCat": "-",
    "faultCategory": "Shut Down",
    "reason": "Shut Down",
    "actionTaken": "after power restoration started the department",
    "shift": "A",
    "technician": "Makki Khan",
    "timeStart": "13:34",
    "timeFinish": "14:30",
    "downtime": "00:56",
    "remarks": ""
  },
  {
    "id": "seed-19",
    "date": "2026-06-09",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_G33",
    "machineNo": "10",
    "deviceDetail": "Doffer",
    "deviceSubCat": "B150",
    "faultCategory": "Doffer Position",
    "reason": "Doffer Position",
    "actionTaken": "checked  and started the machine",
    "shift": "A",
    "technician": "M. Mazhar",
    "timeStart": "13:15",
    "timeFinish": "13:34",
    "downtime": "00:19",
    "remarks": ""
  },
  {
    "id": "seed-20",
    "date": "2026-06-09",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_G33",
    "machineNo": "14",
    "deviceDetail": "",
    "deviceSubCat": "-",
    "faultCategory": "230-No Connection to Machine",
    "reason": "230-No Connection to Machine",
    "actionTaken": "checked and took all the necessary measurement with senior and started the machine",
    "shift": "B",
    "technician": "Makki Khan",
    "timeStart": "16:40",
    "timeFinish": "17:00",
    "downtime": "00:20",
    "remarks": ""
  },
  {
    "id": "seed-21",
    "date": "2026-06-10",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Card_C60",
    "machineNo": "9",
    "deviceDetail": "Sensor",
    "deviceSubCat": "B7",
    "faultCategory": "Sensor",
    "reason": "Sensor",
    "actionTaken": "rectify the sensor and started the machine",
    "shift": "A",
    "technician": "M. Mazhar",
    "timeStart": "10:00",
    "timeFinish": "10:50",
    "downtime": "00:50",
    "remarks": ""
  },
  {
    "id": "seed-22",
    "date": "2026-06-10",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_G33",
    "machineNo": "10",
    "deviceDetail": "Doffer",
    "deviceSubCat": "B109",
    "faultCategory": "Doff Fault",
    "reason": "Doff Fault",
    "actionTaken": "checked  and started the machine",
    "shift": "A",
    "technician": "Makki Khan",
    "timeStart": "09:22",
    "timeFinish": "09:40",
    "downtime": "00:18",
    "remarks": ""
  },
  {
    "id": "seed-23",
    "date": "2026-06-11",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_G33",
    "machineNo": "7",
    "deviceDetail": "Doffer",
    "deviceSubCat": "-",
    "faultCategory": "Doffer Position",
    "reason": "Doffer Position",
    "actionTaken": "checked and took all the necessary action then started the machine",
    "shift": "A",
    "technician": "M. Mazhar",
    "timeStart": "07:00",
    "timeFinish": "07:25",
    "downtime": "00:25",
    "remarks": ""
  },
  {
    "id": "seed-24",
    "date": "2026-06-11",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_G33",
    "machineNo": "10",
    "deviceDetail": "Inverter_VFD",
    "deviceSubCat": "U80, U90",
    "faultCategory": "Machine Washout",
    "reason": "Machine Washout",
    "actionTaken": "checked motors and inverters and started the machine",
    "shift": "B",
    "technician": "Makki Khan",
    "timeStart": "16:45",
    "timeFinish": "17:36",
    "downtime": "00:51",
    "remarks": ""
  },
  {
    "id": "seed-25",
    "date": "2026-06-12",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_G33",
    "machineNo": "10",
    "deviceDetail": "Inverter_VFD",
    "deviceSubCat": "U1, U60, U80, U90",
    "faultCategory": "Machine Washout",
    "reason": "Rotation Monitoring",
    "actionTaken": "programmed the inverters and started the machine",
    "shift": "C+A",
    "technician": "M. Rauf",
    "timeStart": "06:20",
    "timeFinish": "07:30",
    "downtime": "01:10",
    "remarks": ""
  },
  {
    "id": "seed-26",
    "date": "2026-06-12",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_G33",
    "machineNo": "9",
    "deviceDetail": "sensor",
    "deviceSubCat": "B312",
    "faultCategory": "Sensor Not Working",
    "reason": "Sensor Not Working",
    "actionTaken": "replaced the sensor and started the machine",
    "shift": "A",
    "technician": "Makki Khan",
    "timeStart": "10:30",
    "timeFinish": "12:00",
    "downtime": "01:30",
    "remarks": ""
  },
  {
    "id": "seed-27",
    "date": "2026-06-12",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Card_C70",
    "machineNo": "2",
    "deviceDetail": "Motor",
    "deviceSubCat": "M12",
    "faultCategory": "Abnormal Sound in Motor",
    "reason": "Abnormal Sound in Motor",
    "actionTaken": "open its connection and service the motor then started the machine",
    "shift": "A",
    "technician": "M. Mazhar",
    "timeStart": "11:20",
    "timeFinish": "12:20",
    "downtime": "01:00",
    "remarks": ""
  },
  {
    "id": "seed-28",
    "date": "2026-06-12",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_G33",
    "machineNo": "14",
    "deviceDetail": "Emergency_Switch",
    "deviceSubCat": "-",
    "faultCategory": "Emergency",
    "reason": "Emergency",
    "actionTaken": "checked and started the machine",
    "shift": "B",
    "technician": "M. Mazhar",
    "timeStart": "15:25",
    "timeFinish": "15:33",
    "downtime": "00:08",
    "remarks": ""
  },
  {
    "id": "seed-29",
    "date": "2026-06-12",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_K45",
    "machineNo": "6",
    "deviceDetail": "",
    "deviceSubCat": "-",
    "faultCategory": "Communication Error",
    "reason": "Communication Error",
    "actionTaken": "reset from the main and started the machine",
    "shift": "B",
    "technician": "Afaq",
    "timeStart": "21:00",
    "timeFinish": "21:15",
    "downtime": "00:15",
    "remarks": ""
  },
  {
    "id": "seed-30",
    "date": "2026-06-12",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_G33",
    "machineNo": "14",
    "deviceDetail": "Communication Error",
    "deviceSubCat": "Communication Error",
    "faultCategory": "I/O Module",
    "reason": "I/O Module",
    "actionTaken": "reset the machine and took all the necessary measurement then started the machine",
    "shift": "C",
    "technician": "Afaq",
    "timeStart": "01:00",
    "timeFinish": "01:20",
    "downtime": "00:30",
    "remarks": ""
  },
  {
    "id": "seed-31",
    "date": "2026-06-13",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_G33",
    "machineNo": "9",
    "deviceDetail": "Communication Error",
    "deviceSubCat": "Communication Error",
    "faultCategory": "I/O Module",
    "reason": "I/O Module",
    "actionTaken": "checked and restart the   machine",
    "shift": "A",
    "technician": "M. Mazhar",
    "timeStart": "12:35",
    "timeFinish": "12:50",
    "downtime": "00:15",
    "remarks": ""
  },
  {
    "id": "seed-32",
    "date": "2026-06-13",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Lift",
    "machineNo": "1",
    "deviceDetail": "Inverter_VFD",
    "deviceSubCat": "-",
    "faultCategory": "Lift Not Working",
    "reason": "Lift Not Working",
    "actionTaken": "replaced the inverter and started the lift",
    "shift": "B+C",
    "technician": "M. Rauf",
    "timeStart": "20:20",
    "timeFinish": "01:35",
    "downtime": "05:15",
    "remarks": ""
  },
  {
    "id": "seed-33",
    "date": "2026-06-13",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_K45",
    "machineNo": "1",
    "deviceDetail": "Circuit_Breaker ",
    "deviceSubCat": "Q6",
    "faultCategory": "NO Point Missing",
    "reason": "NO Point Missing",
    "actionTaken": "cleaned the breaker and started the machine",
    "shift": "C",
    "technician": "M. Rauf",
    "timeStart": "02:15",
    "timeFinish": "02:37",
    "downtime": "00:22",
    "remarks": ""
  },
  {
    "id": "seed-34",
    "date": "2026-06-13",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_G33",
    "machineNo": "14",
    "deviceDetail": "Limit_Switch",
    "deviceSubCat": "S20",
    "faultCategory": "Switch Fault",
    "reason": "Switch Fault",
    "actionTaken": "checked the switch and started the machine",
    "shift": "C",
    "technician": "Afaq",
    "timeStart": "02:21",
    "timeFinish": "02:37",
    "downtime": "00:16",
    "remarks": ""
  },
  {
    "id": "seed-35",
    "date": "2026-06-13",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Card_C60",
    "machineNo": "6",
    "deviceDetail": "Inverter_VFD",
    "deviceSubCat": "U1",
    "faultCategory": "Communication Error",
    "reason": "Communication Error",
    "actionTaken": "cheeked the communication jack and then started the machine",
    "shift": "C",
    "technician": "M. Rauf",
    "timeStart": "06:15",
    "timeFinish": "06:40",
    "downtime": "00:25",
    "remarks": ""
  },
  {
    "id": "seed-36",
    "date": "2026-06-14",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Filter_Comber ",
    "machineNo": "1",
    "deviceDetail": "Inverter_VFD",
    "deviceSubCat": "-",
    "faultCategory": "Over Heat",
    "reason": "Over Heat",
    "actionTaken": "Cleaned the inverter and started machine",
    "shift": "B",
    "technician": "M. Rauf",
    "timeStart": "21:20",
    "timeFinish": "21:45",
    "downtime": "00:25",
    "remarks": ""
  },
  {
    "id": "seed-37",
    "date": "2026-06-15",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_G33",
    "machineNo": "13",
    "deviceDetail": "sensor",
    "deviceSubCat": "-",
    "faultCategory": "Counter Measurement",
    "reason": "Counter Measurement",
    "actionTaken": "checked the inverter and encoder and started the machine",
    "shift": "A",
    "technician": "M. Mazhar",
    "timeStart": "10:15",
    "timeFinish": "11:40",
    "downtime": "01:25",
    "remarks": ""
  },
  {
    "id": "seed-38",
    "date": "2026-06-15",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_G33",
    "machineNo": "10",
    "deviceDetail": "Inverter_VFD",
    "deviceSubCat": "u60",
    "faultCategory": "Malfunction Converter Drive Fault",
    "reason": "Malfunction Converter Drive Fault",
    "actionTaken": "checked the inverter, motors  and coolant then started the machine",
    "shift": "A",
    "technician": "M. Mazhar",
    "timeStart": "13:25",
    "timeFinish": "13:49",
    "downtime": "00:24",
    "remarks": ""
  },
  {
    "id": "seed-39",
    "date": "2026-06-15",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_G33",
    "machineNo": "9",
    "deviceDetail": "Safety_Switch ",
    "deviceSubCat": "-",
    "faultCategory": "NO Point Missing",
    "reason": "NO Point Missing",
    "actionTaken": "checked and took the necessary measurement then started the machine",
    "shift": "B",
    "technician": "Makki Khan",
    "timeStart": "20:27",
    "timeFinish": "20:36",
    "downtime": "00:09",
    "remarks": ""
  },
  {
    "id": "seed-40",
    "date": "2026-06-15",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_G33",
    "machineNo": "14",
    "deviceDetail": "Relay",
    "deviceSubCat": "K20",
    "faultCategory": "Machine Washout",
    "reason": "Machine Washout",
    "actionTaken": "relaced the relay and started the machine",
    "shift": "B",
    "technician": "Makki Khan",
    "timeStart": "01:00",
    "timeFinish": "01:42",
    "downtime": "00:25",
    "remarks": ""
  },
  {
    "id": "seed-41",
    "date": "2026-06-15",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_G33",
    "machineNo": "10",
    "deviceDetail": "Doffer",
    "deviceSubCat": "B103",
    "faultCategory": "Doffer Position",
    "reason": "Doffer Position",
    "actionTaken": "cheeked it to the fitter and started the machine",
    "shift": "C",
    "technician": "M. Rauf",
    "timeStart": "05:15",
    "timeFinish": "05:28",
    "downtime": "00:13",
    "remarks": ""
  },
  {
    "id": "seed-42",
    "date": "2026-06-16",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_G33",
    "machineNo": "10",
    "deviceDetail": "Inverter_VFD",
    "deviceSubCat": "U60",
    "faultCategory": "Malfunctioning",
    "reason": "Malfunctioning",
    "actionTaken": "replaced the inverter from the lab and started the machine",
    "shift": "A",
    "technician": "M. Mazhar",
    "timeStart": "12:34",
    "timeFinish": "14:34",
    "downtime": "02:00",
    "remarks": ""
  },
  {
    "id": "seed-43",
    "date": "2026-06-16",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Comber",
    "machineNo": "4",
    "deviceDetail": "Drafting",
    "deviceSubCat": "-",
    "faultCategory": "Wire Breakage",
    "reason": "Wire Breakage",
    "actionTaken": "repair the wire and started the machine ",
    "shift": "B",
    "technician": "Makki Khan",
    "timeStart": "22:45",
    "timeFinish": "23:10",
    "downtime": "00:30",
    "remarks": ""
  },
  {
    "id": "seed-44",
    "date": "2026-06-17",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_K45",
    "machineNo": "4",
    "deviceDetail": "Inverter_VFD",
    "deviceSubCat": "U80",
    "faultCategory": "208-Fault on Display",
    "reason": "208-Fault on Display",
    "actionTaken": "cheeked motors, inverters and started the machine",
    "shift": "A",
    "technician": "M. Mazhar",
    "timeStart": "11:47",
    "timeFinish": "12:48",
    "downtime": "01:01",
    "remarks": ""
  },
  {
    "id": "seed-45",
    "date": "2026-06-17",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Simplex",
    "machineNo": "4",
    "deviceDetail": "Safety_Switch ",
    "deviceSubCat": "S20",
    "faultCategory": "Emergency Switch",
    "reason": "Emergency Switch",
    "actionTaken": "cheeked the emergency switch then started machine",
    "shift": "B",
    "technician": "M. Rauf",
    "timeStart": "19:40",
    "timeFinish": "20:00",
    "downtime": "00:20",
    "remarks": ""
  },
  {
    "id": "seed-46",
    "date": "2026-06-18",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_G33",
    "machineNo": "10",
    "deviceDetail": "Sensor",
    "deviceSubCat": "B103",
    "faultCategory": "Sensor Not Working",
    "reason": "Sensor Not Working",
    "actionTaken": "replaced the sensor and started the machine",
    "shift": "A",
    "technician": "M. Mazhar",
    "timeStart": "10:29",
    "timeFinish": "10:52",
    "downtime": "00:23",
    "remarks": ""
  },
  {
    "id": "seed-47",
    "date": "2026-06-18",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Card_C70",
    "machineNo": "4",
    "deviceDetail": "Display",
    "deviceSubCat": "HMI",
    "faultCategory": "Display",
    "reason": "Display",
    "actionTaken": "repair the display from the lab and started the machine",
    "shift": "A",
    "technician": "M. Mazhar",
    "timeStart": "11:30",
    "timeFinish": "13:00",
    "downtime": "01:30",
    "remarks": ""
  },
  {
    "id": "seed-48",
    "date": "2026-06-18",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "AutoCone_21C",
    "machineNo": "2",
    "deviceDetail": "Sensor",
    "deviceSubCat": "039D",
    "faultCategory": "Sensor",
    "reason": "Sensor",
    "actionTaken": "replaced the sensor and started the machine",
    "shift": "B",
    "technician": "Makki Khan",
    "timeStart": "20:00",
    "timeFinish": "20:30",
    "downtime": "00:30",
    "remarks": ""
  },
  {
    "id": "seed-49",
    "date": "2026-06-18",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Simplex",
    "machineNo": "6",
    "deviceDetail": "drive",
    "deviceSubCat": "-",
    "faultCategory": "Communication Error",
    "reason": "Communication Error",
    "actionTaken": "checked loosing and cleaned it then started the machine",
    "shift": "C",
    "technician": "M. Rauf",
    "timeStart": "03:00",
    "timeFinish": "03:30",
    "downtime": "00:30",
    "remarks": ""
  },
  {
    "id": "seed-50",
    "date": "2026-06-19",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_G33",
    "machineNo": "8",
    "deviceDetail": "Limit_Switch",
    "deviceSubCat": "S21",
    "faultCategory": "Limit Switch",
    "reason": "Limit Switch",
    "actionTaken": "cheeked and started the machine",
    "shift": "A",
    "technician": "M. Mazhar",
    "timeStart": "14:30",
    "timeFinish": "14:59",
    "downtime": "00:29",
    "remarks": ""
  },
  {
    "id": "seed-51",
    "date": "2026-06-19",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_G33",
    "machineNo": "10",
    "deviceDetail": "Inverter_VFD",
    "deviceSubCat": "U80",
    "faultCategory": "Machine Washout",
    "reason": "Malfunctioning",
    "actionTaken": "checked inverter , motors and then started the machine",
    "shift": "B",
    "technician": "Makki Khan",
    "timeStart": "21:55",
    "timeFinish": "22:10",
    "downtime": "00:15",
    "remarks": ""
  },
  {
    "id": "seed-52",
    "date": "2026-06-19",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Simplex",
    "machineNo": "4",
    "deviceDetail": "Safety_Switch ",
    "deviceSubCat": "S21",
    "faultCategory": "Emergency Switch",
    "reason": "Emergency Switch",
    "actionTaken": "cheeked and started the machine",
    "shift": "B",
    "technician": "Makki Khan",
    "timeStart": "22:20",
    "timeFinish": "22:35",
    "downtime": "00:15",
    "remarks": ""
  },
  {
    "id": "seed-53",
    "date": "2026-06-19",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Simplex",
    "machineNo": "6",
    "deviceDetail": "Sensor",
    "deviceSubCat": "Breakage Sensor",
    "faultCategory": "Machine Washout",
    "reason": "Machine Washout",
    "actionTaken": "checked all the push buttons and then started the machine ",
    "shift": "C",
    "technician": "Makki Khan",
    "timeStart": "00:30",
    "timeFinish": "01:00",
    "downtime": "00:30",
    "remarks": ""
  },
  {
    "id": "seed-54",
    "date": "2026-06-20",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Simplex",
    "machineNo": "4",
    "deviceDetail": "Communication Error",
    "deviceSubCat": "Communication Error",
    "faultCategory": "Table Sensor",
    "reason": "Table Sensor",
    "actionTaken": "emptied the doff and started the machine ",
    "shift": "C",
    "technician": "M. Rauf",
    "timeStart": "03:50",
    "timeFinish": "04:15",
    "downtime": "00:25",
    "remarks": ""
  },
  {
    "id": "seed-55",
    "date": "2026-06-22",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_G33",
    "machineNo": "10",
    "deviceDetail": "Sensor",
    "deviceSubCat": "-",
    "faultCategory": "Rotation Monitoring",
    "reason": "Rotation Monitoring",
    "actionTaken": "checked sensors and jack loosing then  started the machine",
    "shift": "A",
    "technician": "M. Mazhar",
    "timeStart": "13:50",
    "timeFinish": "14:20",
    "downtime": "00:30",
    "remarks": ""
  },
  {
    "id": "seed-56",
    "date": "2026-06-22",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_G33",
    "machineNo": "7",
    "deviceDetail": "Inverter_VFD",
    "deviceSubCat": "U301",
    "faultCategory": "Inverter_VFD",
    "reason": "Inverter_VFD",
    "actionTaken": "checked sensors and jack loosing then  started the machine",
    "shift": "B",
    "technician": "M. Mazhar",
    "timeStart": "17:15",
    "timeFinish": "18:00",
    "downtime": "00:45",
    "remarks": ""
  },
  {
    "id": "seed-57",
    "date": "2026-06-22",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Card_C60",
    "machineNo": "9",
    "deviceDetail": "Sensor",
    "deviceSubCat": "B2",
    "faultCategory": "Sensor",
    "reason": "Sensor",
    "actionTaken": "replaced the sensor and started the machine",
    "shift": "B",
    "technician": "Makki Khan",
    "timeStart": "16:00",
    "timeFinish": "17:30",
    "downtime": "01:30",
    "remarks": ""
  },
  {
    "id": "seed-58",
    "date": "2026-06-22",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_G33",
    "machineNo": "9",
    "deviceDetail": "Sensor",
    "deviceSubCat": "-",
    "faultCategory": "Sensor Not Working",
    "reason": "Sensor Jack Loosening",
    "actionTaken": "checked and started the machine",
    "shift": "B",
    "technician": "M. Rauf",
    "timeStart": "15:00",
    "timeFinish": "15:30",
    "downtime": "00:30",
    "remarks": ""
  },
  {
    "id": "seed-59",
    "date": "2026-06-22",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_G33",
    "machineNo": "8",
    "deviceDetail": "Doffer",
    "deviceSubCat": "-",
    "faultCategory": "Doffer Position",
    "reason": "Doffer Position",
    "actionTaken": "checked and started the machine",
    "shift": "B",
    "technician": "Afaq",
    "timeStart": "15:15",
    "timeFinish": "15:30",
    "downtime": "00:15",
    "remarks": ""
  },
  {
    "id": "seed-60",
    "date": "2026-06-23",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_G33",
    "machineNo": "7",
    "deviceDetail": "Inverter_VFD",
    "deviceSubCat": "U301",
    "faultCategory": "Inverter_VFD",
    "reason": "Inverter_VFD",
    "actionTaken": "replaced the inverter and started the machine",
    "shift": "B",
    "technician": "Makki Khan",
    "timeStart": "10:30",
    "timeFinish": "10:50",
    "downtime": "00:20",
    "remarks": ""
  },
  {
    "id": "seed-61",
    "date": "2026-06-24",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_G33",
    "machineNo": "9",
    "deviceDetail": "Inverter_VFD",
    "deviceSubCat": "U1",
    "faultCategory": "Inverter Fault",
    "reason": "Inverter Fault",
    "actionTaken": "checked the inverter and took the necessary actin then started the machine",
    "shift": "B",
    "technician": "Afaq",
    "timeStart": "20:40",
    "timeFinish": "20:55",
    "downtime": "01:10",
    "remarks": ""
  },
  {
    "id": "seed-62",
    "date": "2026-06-25",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_K45",
    "machineNo": "3",
    "deviceDetail": "Communication Error",
    "deviceSubCat": "-",
    "faultCategory": "Communication Error",
    "reason": "Communication Error",
    "actionTaken": "checked and programmed cold start and then started the machine",
    "shift": "B",
    "technician": "Afaq",
    "timeStart": "22:45",
    "timeFinish": "23:15",
    "downtime": "00:30",
    "remarks": ""
  },
  {
    "id": "seed-63",
    "date": "2026-06-26",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_G33",
    "machineNo": "7",
    "deviceDetail": "Limit_Switch",
    "deviceSubCat": "S21",
    "faultCategory": "Counter Measurement",
    "reason": "Counter Measurement",
    "actionTaken": "checked and reset then started the machine",
    "shift": "A",
    "technician": "M. Mazhar",
    "timeStart": "07:43",
    "timeFinish": "08:00",
    "downtime": "00:17",
    "remarks": ""
  },
  {
    "id": "seed-64",
    "date": "2026-06-27",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_G33",
    "machineNo": "14",
    "deviceDetail": "Communication Error",
    "deviceSubCat": "-",
    "faultCategory": "Malfunctioning",
    "reason": "Malfunctioning",
    "actionTaken": "checked and started the machine",
    "shift": "A",
    "technician": "M. Mazhar",
    "timeStart": "13:30",
    "timeFinish": "13:50",
    "downtime": "01:10",
    "remarks": ""
  },
  {
    "id": "seed-65",
    "date": "2026-06-27",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Drawing_Finisher",
    "machineNo": "6",
    "deviceDetail": "Power_Supply",
    "deviceSubCat": "Communication",
    "faultCategory": "Communication Error",
    "reason": "Communication Error",
    "actionTaken": "checked jack loosing and started the machine",
    "shift": "A",
    "technician": "M. Mazhar",
    "timeStart": "11:40",
    "timeFinish": "11:55",
    "downtime": "05:00",
    "remarks": ""
  },
  {
    "id": "seed-66",
    "date": "2026-06-28",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Drawing_Finisher",
    "machineNo": "1",
    "deviceDetail": "Sensor",
    "deviceSubCat": "B2",
    "faultCategory": "Sensor",
    "reason": "Sensor",
    "actionTaken": "checked and started the machine",
    "shift": "A",
    "technician": "M. Mazhar",
    "timeStart": "10:00",
    "timeFinish": "10:20",
    "downtime": "00:20",
    "remarks": ""
  },
  {
    "id": "seed-67",
    "date": "2026-06-28",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_G33",
    "machineNo": "7",
    "deviceDetail": "Ring_Rail",
    "deviceSubCat": "-",
    "faultCategory": "Ring_Rail",
    "reason": "Ring_Rail",
    "actionTaken": "checked and started the machine",
    "shift": "C",
    "technician": "Afaq",
    "timeStart": "02:30",
    "timeFinish": "03:00",
    "downtime": "00:30",
    "remarks": ""
  },
  {
    "id": "seed-68",
    "date": "2026-06-29",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_G33",
    "machineNo": "7",
    "deviceDetail": "Ring_Rail",
    "deviceSubCat": "-",
    "faultCategory": "Ring_Rail",
    "reason": "Ring_Rail",
    "actionTaken": "checked and started the machine",
    "shift": "B",
    "technician": "Afaq",
    "timeStart": "21:10",
    "timeFinish": "21:20",
    "downtime": "00:10",
    "remarks": ""
  },
  {
    "id": "seed-69",
    "date": "2026-06-29",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_G33",
    "machineNo": "9",
    "deviceDetail": "Doffer",
    "deviceSubCat": "-",
    "faultCategory": "Doffer Position",
    "reason": "Doffer Position",
    "actionTaken": "cold start the programmed and start the machine",
    "shift": "B",
    "technician": "M. Rauf",
    "timeStart": "21:30",
    "timeFinish": "21:50",
    "downtime": "00:20",
    "remarks": ""
  },
  {
    "id": "seed-70",
    "date": "2026-06-30",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Drawing_Breaker",
    "machineNo": "5",
    "deviceDetail": "Pressure_Switch_Transducer",
    "deviceSubCat": "S20",
    "faultCategory": "Push_Buttons",
    "reason": "NO Point Missing",
    "actionTaken": "replaced the push button and started the machine",
    "shift": "A",
    "technician": "M. Mazhar",
    "timeStart": "12:20",
    "timeFinish": "12:50",
    "downtime": "00:30",
    "remarks": ""
  },
  {
    "id": "seed-71",
    "date": "2026-06-30",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_G33",
    "machineNo": "7",
    "deviceDetail": "Ring_Rail",
    "deviceSubCat": "-",
    "faultCategory": "Ring_Rail",
    "reason": "Ring Rail",
    "actionTaken": "checked and started the machine",
    "shift": "B",
    "technician": "M. Mazhar",
    "timeStart": "15:50",
    "timeFinish": "16:10",
    "downtime": "00:20",
    "remarks": ""
  },
  {
    "id": "seed-72",
    "date": "2026-06-30",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_K45",
    "machineNo": "5",
    "deviceDetail": "Inverter_VFD",
    "deviceSubCat": "u80",
    "faultCategory": "Inverter Fault",
    "reason": "Inverter Fault",
    "actionTaken": "checked al the inverters, motors and cold start the programmed then started the machine",
    "shift": "B",
    "technician": "M. Mazhar",
    "timeStart": "16:50",
    "timeFinish": "17:30",
    "downtime": "00:40",
    "remarks": ""
  },
  {
    "id": "seed-73",
    "date": "2026-06-30",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_G33",
    "machineNo": "7",
    "deviceDetail": "Motor",
    "deviceSubCat": "Suction Fan",
    "faultCategory": "Motor",
    "reason": "Suction Fan",
    "actionTaken": "replaced the motor ,breaker and then started the machine",
    "shift": "A",
    "technician": "M. Mazhar",
    "timeStart": "09:00",
    "timeFinish": "12:00",
    "downtime": "03:00",
    "remarks": ""
  },
  {
    "id": "seed-74",
    "date": "2026-06-30",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_K45",
    "machineNo": "5",
    "deviceDetail": "Inverter_VFD",
    "deviceSubCat": "U80",
    "faultCategory": "Over Load",
    "reason": "Over Load",
    "actionTaken": "checked the inverters, motors and started the machine",
    "shift": "C",
    "technician": "Afaq",
    "timeStart": "01:00",
    "timeFinish": "01:30",
    "downtime": "00:30",
    "remarks": ""
  },
  {
    "id": "seed-75",
    "date": "2026-06-30",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_G33",
    "machineNo": "7",
    "deviceDetail": "Ring_Rail",
    "deviceSubCat": "-",
    "faultCategory": "Ring_Rail",
    "reason": "Ring Rail Position Out",
    "actionTaken": "checked and started the machine",
    "shift": "C",
    "technician": "Afaq",
    "timeStart": "05:40",
    "timeFinish": "05:55",
    "downtime": "00:15",
    "remarks": ""
  }
]

MACHINES = [
  "A_11",
  "AutoCone_21C",
  "Card_C60",
  "Card_C70",
  "Comber",
  "Complete",
  "Drawing_Breaker",
  "Drawing_Finisher",
  "Filter_Comber",
  "Lift",
  "Ring_G33",
  "Ring_K45",
  "Simplex"
]

SHIFTS = [
  "A",
  "B",
  "C",
  "A+B",
  "B+C",
  "C+A"
]

FAULT_CATEGORIES = [
  "208-Fault on Display",
  "230-No Connection to Machine",
  "Abnormal Sound in Motor",
  "CBF Conveyor",
  "Communication Error",
  "Coolant Leakage",
  "Counter Measurement",
  "Display",
  "Doff Fault",
  "Doffer Position",
  "Emergency",
  "Emergency Switch",
  "I/O Module",
  "Inverter Fault",
  "Inverter_VFD",
  "Jack Loosing",
  "Lift Not Working",
  "Limit Switch",
  "Low Pressure",
  "Machine Washout",
  "Malfunction Converter Drive Fault",
  "Malfunctioning",
  "Motor",
  "NO Point Missing",
  "Over Heat",
  "Over Load",
  "Pressure_Switch_Transducer",
  "Push_Buttons",
  "Ring_Rail",
  "Rotation Monitoring",
  "Safety Circuit",
  "Sensor",
  "Sensor Not Working",
  "Shut Down",
  "Switch Fault",
  "Table Sensor",
  "Wire Breakage"
]

TECHNICIANS = [
  "Abdul Rehman",
  "Adnan Faridi",
  "Afaq",
  "Ahmad",
  "Aleem",
  "Anas",
  "Arif",
  "Bilal",
  "Fahad",
  "Farrukh Zaman",
  "Kashif",
  "M. Adnan",
  "M. Mazhar",
  "M. Rauf",
  "Makki Khan",
  "Mehboob-ul-Haq",
  "Owais",
  "Shabbir",
  "Waqas",
  "Waseem Akram",
  "Zafar"
]

COMPLAINT_REFERENCES = [
  "Supervisor",
  "Power House"
]

# Starter values for the Notification Type dropdown. These are only used the
# first time the database is created — afterwards the list is managed from
# Settings > Dropdown Lists.
NOTIFICATION_TYPES = [
  "Breakdown",
  "Preventive Maintenance",
  "Electrical",
  "Mechanical",
  "Emergency"
]

DEVICE_DETAILS = [
  "Circuit_Breaker",
  "Communication Error",
  "Coolant_Pipes",
  "Display",
  "Doffer",
  "Drafting",
  "Emergency_Switch",
  "Inverter_VFD",
  "Limit_Switch",
  "Low Pressure",
  "Motor",
  "Power_Supply",
  "Pressure_Switch_Transducer",
  "Relay",
  "Ring_Rail",
  "Safety_Switch",
  "Sensor",
  "drive",
  "sensor"
]

DEVICE_SUB_CATEGORIES = [
  "039D",
  "B103",
  "B109",
  "B150",
  "B2",
  "B312",
  "B321",
  "B7",
  "Breakage Sensor",
  "Communication",
  "Communication Error",
  "Coolant_Pipes",
  "F113",
  "HMI",
  "K20",
  "M12",
  "Machine Washout",
  "Q6",
  "S20",
  "S21",
  "SQ23D",
  "Suction Fan",
  "U1",
  "U1, U60, U80, U90",
  "U301",
  "U60",
  "U80",
  "U80, U90",
  "m6",
  "m61",
  "m81",
  "u60",
  "u80"
]

DEFAULT_UNIT_NAME = "Unit-01 - 45mtr"

# ---- Unit-02 (D12) data, uploaded separately ----

UNIT2_NAME = "Unit-02 - D12"

SEED_RECORDS_UNIT2 = [
  {
    "id": "seed-u2-0",
    "date": "2026-06-01",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "AutoCone_QProEX",
    "machineNo": "7",
    "deviceDetail": "CBF",
    "deviceSubCat": "A2",
    "faultCategory": "Loose Connections",
    "reason": "Loose Connections",
    "actionTaken": "Cleaned and tightened the jacks and start the machine",
    "shift": "A",
    "technician": "Makki Khan",
    "timeStart": "10:10",
    "timeFinish": "10:30",
    "downtime": "00:20",
    "remarks": ""
  },
  {
    "id": "seed-u2-1",
    "date": "2026-06-01",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Drawing_Breaker",
    "machineNo": "3",
    "deviceDetail": "HMI",
    "deviceSubCat": "Display",
    "faultCategory": "Jack Loosing",
    "reason": "Jack Loosing",
    "actionTaken": "Display found off, reset the display and start the machine",
    "shift": "B+C",
    "technician": "Afaq",
    "timeStart": "22:45",
    "timeFinish": "23:10",
    "downtime": "00:25",
    "remarks": ""
  },
  {
    "id": "seed-u2-2",
    "date": "2026-06-02",
    "complaintReference": "Power House",
    "ticketNo": "",
    "machine": "Complete",
    "machineNo": "ALL",
    "deviceDetail": "",
    "deviceSubCat": "",
    "faultCategory": "Shut Down",
    "reason": "Shut Down",
    "actionTaken": "After power restoration, department started",
    "shift": "B",
    "technician": "Makki Khan",
    "timeStart": "16:11",
    "timeFinish": "17:15",
    "downtime": "01:04",
    "remarks": ""
  },
  {
    "id": "seed-u2-3",
    "date": "2026-06-03",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Drawing_Finisher",
    "machineNo": "5",
    "deviceDetail": "HMI",
    "deviceSubCat": "Display",
    "faultCategory": "ATL No Communication Fault",
    "reason": "ATL No Communication Fault",
    "actionTaken": "Display stuck on booting, reset the display and start the machine",
    "shift": "B",
    "technician": "M. Mazhar",
    "timeStart": "16:05",
    "timeFinish": "16:20",
    "downtime": "00:15",
    "remarks": ""
  },
  {
    "id": "seed-u2-4",
    "date": "2026-06-03",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Drawing_Finisher",
    "machineNo": "3",
    "deviceDetail": "Motor",
    "deviceSubCat": "M90",
    "faultCategory": "Motor Bearing",
    "reason": "Motor Bearing",
    "actionTaken": "Irregular noise occurrs, change the motor also check the gearbox and start the machine",
    "shift": "B",
    "technician": "Afaq",
    "timeStart": "19:00",
    "timeFinish": "20:30",
    "downtime": "01:30",
    "remarks": ""
  },
  {
    "id": "seed-u2-5",
    "date": "2026-06-03",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Drawing_Finisher",
    "machineNo": "3",
    "deviceDetail": "Drive",
    "deviceSubCat": "G90",
    "faultCategory": "G90 Error",
    "reason": "G90 Error",
    "actionTaken": "Interchange the M90 motor with Machine # 2 (DF) and start the machine",
    "shift": "C",
    "technician": "Afaq",
    "timeStart": "00:30",
    "timeFinish": "01:30",
    "downtime": "01:00",
    "remarks": ""
  },
  {
    "id": "seed-u2-6",
    "date": "2026-06-04",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_G36",
    "machineNo": "7",
    "deviceDetail": "PLC",
    "deviceSubCat": "I/O Module",
    "faultCategory": "Communication Error",
    "reason": "Communication Error",
    "actionTaken": "X20 knot removed occurred, cleaned the module, cold start applied on machine and start the machine",
    "shift": "C",
    "technician": "M. Rauf",
    "timeStart": "00:30",
    "timeFinish": "01:10",
    "downtime": "00:40",
    "remarks": ""
  },
  {
    "id": "seed-u2-7",
    "date": "2026-06-04",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_G36",
    "machineNo": "17",
    "deviceDetail": "Motor",
    "deviceSubCat": "M82",
    "faultCategory": "Over Heat + Over Temperature",
    "reason": "Over Heat + Over Temperature",
    "actionTaken": "After necessary checking of motor start the machine",
    "shift": "C",
    "technician": "M. Rauf",
    "timeStart": "03:00",
    "timeFinish": "03:20",
    "downtime": "00:20",
    "remarks": ""
  },
  {
    "id": "seed-u2-8",
    "date": "2026-06-04",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "AutoCone_QProEX",
    "machineNo": "11",
    "deviceDetail": "Motor",
    "deviceSubCat": "",
    "faultCategory": "Over Voltage",
    "reason": "Over Voltage",
    "actionTaken": "M261 found trip, after necessary checkings motor was replaced and start the machine",
    "shift": "C",
    "technician": "Afaq",
    "timeStart": "04:45",
    "timeFinish": "06:40",
    "downtime": "01:55",
    "remarks": ""
  },
  {
    "id": "seed-u2-9",
    "date": "2026-06-04",
    "complaintReference": "Power House",
    "ticketNo": "",
    "machine": "Complete",
    "machineNo": "ALL",
    "deviceDetail": "",
    "deviceSubCat": "",
    "faultCategory": "Shut Down",
    "reason": "Shut Down",
    "actionTaken": "After power restoration, department started",
    "shift": "C",
    "technician": "Afaq",
    "timeStart": "06:16",
    "timeFinish": "06:50",
    "downtime": "00:34",
    "remarks": ""
  },
  {
    "id": "seed-u2-10",
    "date": "2026-06-05",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_G36",
    "machineNo": "9",
    "deviceDetail": "PLC",
    "deviceSubCat": "I/O Module",
    "faultCategory": "Communication Error",
    "reason": "Communication Error",
    "actionTaken": "X20 knot removed occurred, cleaned the module, cold start applied on machine and start the machine",
    "shift": "B",
    "technician": "Makki Khan",
    "timeStart": "16:30",
    "timeFinish": "17:30",
    "downtime": "01:00",
    "remarks": ""
  },
  {
    "id": "seed-u2-11",
    "date": "2026-06-06",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_G36",
    "machineNo": "11",
    "deviceDetail": "Inverter_VFD",
    "deviceSubCat": "U101",
    "faultCategory": "Over Heat + Over Temperature",
    "reason": "Over Heat + Over Temperature",
    "actionTaken": "Cleaned the inverter and start the machine",
    "shift": "A",
    "technician": "M. Mazhar",
    "timeStart": "12:45",
    "timeFinish": "13:00",
    "downtime": "00:15",
    "remarks": ""
  },
  {
    "id": "seed-u2-12",
    "date": "2026-06-06",
    "complaintReference": "Power House",
    "ticketNo": "",
    "machine": "Complete",
    "machineNo": "ALL",
    "deviceDetail": "",
    "deviceSubCat": "",
    "faultCategory": "Shut Down",
    "reason": "Shut Down",
    "actionTaken": "After power restoration, department started",
    "shift": "A",
    "technician": "M. Mazhar",
    "timeStart": "11:33",
    "timeFinish": "12:20",
    "downtime": "00:47",
    "remarks": ""
  },
  {
    "id": "seed-u2-13",
    "date": "2026-06-06",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "AutoCone_QProEX",
    "machineNo": "6",
    "deviceDetail": "CBF",
    "deviceSubCat": "Slave 5",
    "faultCategory": "Coil",
    "reason": "Coil",
    "actionTaken": "broken wire found, repair the wire and start the machine",
    "shift": "C",
    "technician": "M. Rauf",
    "timeStart": "05:15",
    "timeFinish": "06:00",
    "downtime": "00:45",
    "remarks": ""
  },
  {
    "id": "seed-u2-14",
    "date": "2026-06-07",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "AutoCone_QProEX",
    "machineNo": "10",
    "deviceDetail": "CBF",
    "deviceSubCat": "A2",
    "faultCategory": "A2 Fault",
    "reason": "A2 Fault",
    "actionTaken": "tightened the loose jacks and start the machine",
    "shift": "A",
    "technician": "Makki Khan",
    "timeStart": "10:00",
    "timeFinish": "10:30",
    "downtime": "00:30",
    "remarks": ""
  },
  {
    "id": "seed-u2-15",
    "date": "2026-06-07",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Simplex_ElectroJet",
    "machineNo": "9",
    "deviceDetail": "Motor",
    "deviceSubCat": "M2",
    "faultCategory": "Motor",
    "reason": "Motor",
    "actionTaken": "Replace the motor, performed calibration and start the machine",
    "shift": "A",
    "technician": "M. Mazhar",
    "timeStart": "07:00",
    "timeFinish": "14:35",
    "downtime": "07:35",
    "remarks": ""
  },
  {
    "id": "seed-u2-16",
    "date": "2026-06-07",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_G36",
    "machineNo": "12",
    "deviceDetail": "PLC",
    "deviceSubCat": "I/O Module",
    "faultCategory": "Communication Error",
    "reason": "Communication Error",
    "actionTaken": "X20 knot removed occurred, cleaned the module, cold start applied on machine and start the machine",
    "shift": "C",
    "technician": "M. Rauf",
    "timeStart": "02:45",
    "timeFinish": "03:00",
    "downtime": "00:15",
    "remarks": ""
  },
  {
    "id": "seed-u2-17",
    "date": "2026-06-08",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Simplex_ElectroJet",
    "machineNo": "6",
    "deviceDetail": "HMI",
    "deviceSubCat": "Display",
    "faultCategory": "ATL No Communication Fault",
    "reason": "ATL No Communication Fault",
    "actionTaken": "Repaired the display and start the machine",
    "shift": "A",
    "technician": "M. Mazhar",
    "timeStart": "11:30",
    "timeFinish": "15:30",
    "downtime": "04:00",
    "remarks": ""
  },
  {
    "id": "seed-u2-18",
    "date": "2026-06-08",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Drawing_Finisher",
    "machineNo": "2",
    "deviceDetail": "PLC",
    "deviceSubCat": "I/O Module",
    "faultCategory": "Communication Error",
    "reason": "Communication Error",
    "actionTaken": "Reset the communication error and start the machine",
    "shift": "A",
    "technician": "M. Mazhar",
    "timeStart": "12:10",
    "timeFinish": "12:30",
    "downtime": "00:20",
    "remarks": ""
  },
  {
    "id": "seed-u2-19",
    "date": "2026-06-09",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "AutoCone_QProEX",
    "machineNo": "2",
    "deviceDetail": "CBF",
    "deviceSubCat": "A2",
    "faultCategory": "A2 Fault",
    "reason": "A2 Fault",
    "actionTaken": "Reset the communication error and start the machine",
    "shift": "B",
    "technician": "M. Mazhar",
    "timeStart": "16:00",
    "timeFinish": "16:50",
    "downtime": "00:50",
    "remarks": ""
  },
  {
    "id": "seed-u2-20",
    "date": "2026-06-09",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Card_C70",
    "machineNo": "1",
    "deviceDetail": "Sensor",
    "deviceSubCat": "B7",
    "faultCategory": "Wire Breakage",
    "reason": "Wire Breakage",
    "actionTaken": "Repaired the broken wire and start the machine",
    "shift": "C",
    "technician": "Afaq",
    "timeStart": "01:45",
    "timeFinish": "02:10",
    "downtime": "00:25",
    "remarks": ""
  },
  {
    "id": "seed-u2-21",
    "date": "2026-06-10",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Card_C70",
    "machineNo": "1",
    "deviceDetail": "Sensor",
    "deviceSubCat": "B7",
    "faultCategory": "Wire Breakage",
    "reason": "Wire Breakage",
    "actionTaken": "Replace the sensor and start the machine",
    "shift": "A",
    "technician": "Makki Khan",
    "timeStart": "08:30",
    "timeFinish": "09:00",
    "downtime": "00:30",
    "remarks": ""
  },
  {
    "id": "seed-u2-22",
    "date": "2026-06-10",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Simplex_ElectroJet",
    "machineNo": "9",
    "deviceDetail": "HMI",
    "deviceSubCat": "Display",
    "faultCategory": "ATL No Communication Fault",
    "reason": "ATL No Communication Fault",
    "actionTaken": "Reset the communication error and reprogram the HMI Panel and start the machine",
    "shift": "A",
    "technician": "Makki Khan",
    "timeStart": "12:00",
    "timeFinish": "12:30",
    "downtime": "00:30",
    "remarks": ""
  },
  {
    "id": "seed-u2-23",
    "date": "2026-06-11",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_G36",
    "machineNo": "13",
    "deviceDetail": "Inverter_VFD",
    "deviceSubCat": "U60",
    "faultCategory": "Inverter Fault",
    "reason": "Inverter Fault",
    "actionTaken": "Cleaned the inverter and start the machine",
    "shift": "A",
    "technician": "Makki Khan",
    "timeStart": "12:45",
    "timeFinish": "13:05",
    "downtime": "00:20",
    "remarks": ""
  },
  {
    "id": "seed-u2-24",
    "date": "2026-06-11",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "A_11",
    "machineNo": "1",
    "deviceDetail": "Circuit_Breaker",
    "deviceSubCat": "Q6",
    "faultCategory": "Circuit Breaker Trip",
    "reason": "Circuit Breaker Trip",
    "actionTaken": "After necessary checking, start the machine",
    "shift": "B",
    "technician": "Makki Khan",
    "timeStart": "17:20",
    "timeFinish": "17:40",
    "downtime": "00:20",
    "remarks": ""
  },
  {
    "id": "seed-u2-25",
    "date": "2026-06-12",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Comber",
    "machineNo": "3",
    "deviceDetail": "Sensor",
    "deviceSubCat": "B3",
    "faultCategory": "Loose Connections",
    "reason": "Loose Connections",
    "actionTaken": "Cleaned the sensor and start the machine",
    "shift": "C",
    "technician": "Afaq",
    "timeStart": "00:25",
    "timeFinish": "00:40",
    "downtime": "00:15",
    "remarks": ""
  },
  {
    "id": "seed-u2-26",
    "date": "2026-06-12",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_G36",
    "machineNo": "14",
    "deviceDetail": "PLC",
    "deviceSubCat": "I/O Module",
    "faultCategory": "Communication Error",
    "reason": "Communication Error",
    "actionTaken": "X20 knot removed occurred, cleaned the module, cold start applied on machine and start the machine",
    "shift": "C",
    "technician": "Afaq",
    "timeStart": "01:00",
    "timeFinish": "01:20",
    "downtime": "00:20",
    "remarks": ""
  },
  {
    "id": "seed-u2-27",
    "date": "2026-06-13",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_G36",
    "machineNo": "11",
    "deviceDetail": "Inverter_VFD",
    "deviceSubCat": "U11",
    "faultCategory": "Over Heat + Over Temperature",
    "reason": "Over Heat + Over Temperature",
    "actionTaken": "Cleaned the inverter and start the machine",
    "shift": "C",
    "technician": "M. Rauf",
    "timeStart": "01:20",
    "timeFinish": "01:45",
    "downtime": "00:25",
    "remarks": ""
  },
  {
    "id": "seed-u2-28",
    "date": "2026-06-14",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Simplex_ElectroJet",
    "machineNo": "9",
    "deviceDetail": "Drive",
    "deviceSubCat": "",
    "faultCategory": "Can Bus Communication",
    "reason": "Can Bus Communication",
    "actionTaken": "Reset the communication error and start the machine",
    "shift": "B",
    "technician": "M. Rauf",
    "timeStart": "19:15",
    "timeFinish": "19:35",
    "downtime": "00:20",
    "remarks": ""
  },
  {
    "id": "seed-u2-29",
    "date": "2026-06-16",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Simplex_ElectroJet",
    "machineNo": "2",
    "deviceDetail": "Drive",
    "deviceSubCat": "",
    "faultCategory": "Can Bus Communication",
    "reason": "Can Bus Communication",
    "actionTaken": "Reset the communication error also check power supply and start the machine",
    "shift": "B",
    "technician": "M. Mazhar",
    "timeStart": "16:00",
    "timeFinish": "16:15",
    "downtime": "10:00",
    "remarks": ""
  },
  {
    "id": "seed-u2-30",
    "date": "2026-06-16",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "AutoCone_QProEX",
    "machineNo": "2",
    "deviceDetail": "CBF",
    "deviceSubCat": "A8",
    "faultCategory": "Emergency Relay",
    "reason": "Emergency Relay",
    "actionTaken": "Cleaned the sensor and start the machine",
    "shift": "C",
    "technician": "Makki Khan",
    "timeStart": "03:35",
    "timeFinish": "03:50",
    "downtime": "00:15",
    "remarks": ""
  },
  {
    "id": "seed-u2-31",
    "date": "2026-06-16",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Drawing_Finisher",
    "machineNo": "5",
    "deviceDetail": "Emergency_Switch",
    "deviceSubCat": "S20",
    "faultCategory": "Emergency Switch",
    "reason": "Emergency Switch",
    "actionTaken": "Cleaned the switch and start the machine",
    "shift": "C",
    "technician": "Makki Khan",
    "timeStart": "00:50",
    "timeFinish": "01:10",
    "downtime": "00:20",
    "remarks": ""
  },
  {
    "id": "seed-u2-32",
    "date": "2026-06-16",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Card_C70",
    "machineNo": "7",
    "deviceDetail": "Motor",
    "deviceSubCat": "M13",
    "faultCategory": "Over Load",
    "reason": "Over Load",
    "actionTaken": "Overheated cable found, replace the cable and start the machine",
    "shift": "C",
    "technician": "Makki Khan",
    "timeStart": "04:10",
    "timeFinish": "05:00",
    "downtime": "00:50",
    "remarks": ""
  },
  {
    "id": "seed-u2-33",
    "date": "2026-06-17",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Drawing_Breaker",
    "machineNo": "2",
    "deviceDetail": "Sensor",
    "deviceSubCat": "B2",
    "faultCategory": "Communication Error",
    "reason": "Communication Error",
    "actionTaken": "Replace the sensor and start the machine",
    "shift": "B",
    "technician": "M. Mazhar",
    "timeStart": "15:30",
    "timeFinish": "16:00",
    "downtime": "00:30",
    "remarks": ""
  },
  {
    "id": "seed-u2-34",
    "date": "2026-06-17",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Drawing_Breaker",
    "machineNo": "7",
    "deviceDetail": "Drive",
    "deviceSubCat": "",
    "faultCategory": "471-Drive Fault",
    "reason": "471-Drive Fault",
    "actionTaken": "Cleaned and reset the drive and start the machine",
    "shift": "C",
    "technician": "Makki Khan",
    "timeStart": "23:15",
    "timeFinish": "23:25",
    "downtime": "00:10",
    "remarks": ""
  },
  {
    "id": "seed-u2-35",
    "date": "2026-06-18",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_G36",
    "machineNo": "17",
    "deviceDetail": "PLC",
    "deviceSubCat": "I/O Module",
    "faultCategory": "Communication Error",
    "reason": "Communication Error",
    "actionTaken": "X20 knot removed occurred, cleaned the module, cold start applied on machine and start the machine",
    "shift": "B",
    "technician": "M. Mazhar",
    "timeStart": "17:20",
    "timeFinish": "17:40",
    "downtime": "00:20",
    "remarks": ""
  },
  {
    "id": "seed-u2-36",
    "date": "2026-06-18",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_G36",
    "machineNo": "17",
    "deviceDetail": "PLC",
    "deviceSubCat": "I/O Module",
    "faultCategory": "Communication Error",
    "reason": "Communication Error",
    "actionTaken": "X20 knot removed re-occurred, cleaned the module, cold start applied on machine and start the machine",
    "shift": "B",
    "technician": "M. Mazhar",
    "timeStart": "18:00",
    "timeFinish": "18:35",
    "downtime": "00:35",
    "remarks": ""
  },
  {
    "id": "seed-u2-37",
    "date": "2026-06-18",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Card_C70",
    "machineNo": "3",
    "deviceDetail": "Inverter_VFD",
    "deviceSubCat": "U12",
    "faultCategory": "ATL No Communication Fault",
    "reason": "ATL No Communication Fault",
    "actionTaken": "Replace the inverter and start the machine",
    "shift": "B",
    "technician": "M. Rauf",
    "timeStart": "21:00",
    "timeFinish": "22:30",
    "downtime": "01:30",
    "remarks": ""
  },
  {
    "id": "seed-u2-38",
    "date": "2026-06-19",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "AutoCone_QProEX",
    "machineNo": "3",
    "deviceDetail": "CBF",
    "deviceSubCat": "A2",
    "faultCategory": "A2 Fault",
    "reason": "A2 Fault",
    "actionTaken": "Check the loosing of slave and start the machine",
    "shift": "A",
    "technician": "M. Mazhar",
    "timeStart": "11:00",
    "timeFinish": "11:20",
    "downtime": "00:20",
    "remarks": ""
  },
  {
    "id": "seed-u2-39",
    "date": "2026-06-19",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_G38",
    "machineNo": "3",
    "deviceDetail": "Sensor",
    "deviceSubCat": "B312",
    "faultCategory": "Sensor Jack Loosening",
    "reason": "Sensor Jack Loosening",
    "actionTaken": "tightened the loose jacks and start the machine",
    "shift": "C",
    "technician": "Makki Khan",
    "timeStart": "01:40",
    "timeFinish": "02:10",
    "downtime": "00:30",
    "remarks": ""
  },
  {
    "id": "seed-u2-40",
    "date": "2026-06-20",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "AutoCone_QProEX",
    "machineNo": "11",
    "deviceDetail": "CBF",
    "deviceSubCat": "A2",
    "faultCategory": "A2 Fault",
    "reason": "A2 Fault",
    "actionTaken": "Check the loosing of slave and start the machine",
    "shift": "A",
    "technician": "M. Mazhar",
    "timeStart": "11:30",
    "timeFinish": "11:45",
    "downtime": "00:15",
    "remarks": ""
  },
  {
    "id": "seed-u2-41",
    "date": "2026-06-22",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Simplex_ElectroJet",
    "machineNo": "10",
    "deviceDetail": "HMI",
    "deviceSubCat": "Display",
    "faultCategory": "ATL No Communication Fault",
    "reason": "ATL No Communication Fault",
    "actionTaken": "Check the loosing of jack and start the machine",
    "shift": "B",
    "technician": "Makki Khan",
    "timeStart": "21:15",
    "timeFinish": "21:30",
    "downtime": "00:15",
    "remarks": ""
  },
  {
    "id": "seed-u2-42",
    "date": "2026-06-22",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_G36",
    "machineNo": "7",
    "deviceDetail": "PLC",
    "deviceSubCat": "I/O Module",
    "faultCategory": "Communication Error",
    "reason": "Communication Error",
    "actionTaken": "X20 knot removed occurred, cleaned the module, cold start applied on machine and start the machine",
    "shift": "C",
    "technician": "Afaq",
    "timeStart": "06:00",
    "timeFinish": "06:40",
    "downtime": "00:40",
    "remarks": ""
  },
  {
    "id": "seed-u2-43",
    "date": "2026-06-23",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "AutoCone_QProEX",
    "machineNo": "2",
    "deviceDetail": "CBF",
    "deviceSubCat": "A2",
    "faultCategory": "Loose Connections",
    "reason": "Loose Connections",
    "actionTaken": "Cleaned and tightened the jacks and start the machine",
    "shift": "A",
    "technician": "M. Mazhar",
    "timeStart": "12:15",
    "timeFinish": "12:30",
    "downtime": "00:15",
    "remarks": ""
  },
  {
    "id": "seed-u2-44",
    "date": "2026-06-23",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_G36",
    "machineNo": "19",
    "deviceDetail": "PLC",
    "deviceSubCat": "I/O Module",
    "faultCategory": "Communication Error",
    "reason": "Communication Error",
    "actionTaken": "X20 knot removed occurred, cleaned the module, cold start applied on machine and start the machine",
    "shift": "A",
    "technician": "M. Mazhar",
    "timeStart": "11:00",
    "timeFinish": "11:20",
    "downtime": "00:20",
    "remarks": ""
  },
  {
    "id": "seed-u2-45",
    "date": "2026-06-24",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_G38",
    "machineNo": "3",
    "deviceDetail": "PLC",
    "deviceSubCat": "I/O Module",
    "faultCategory": "Communication Error",
    "reason": "Communication Error",
    "actionTaken": "X20 knot removed occurred, cleaned the module, cold start applied on machine and start the machine",
    "shift": "A",
    "technician": "M. Mazhar",
    "timeStart": "13:00",
    "timeFinish": "13:15",
    "downtime": "00:15",
    "remarks": ""
  },
  {
    "id": "seed-u2-46",
    "date": "2026-06-24",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_G38",
    "machineNo": "3",
    "deviceDetail": "Ring_Rail",
    "deviceSubCat": "",
    "faultCategory": "Ring Rail Position Out",
    "reason": "Ring Rail Position Out",
    "actionTaken": "After necessary checking start the machine",
    "shift": "A",
    "technician": "M. Mazhar",
    "timeStart": "14:20",
    "timeFinish": "14:45",
    "downtime": "00:25",
    "remarks": ""
  },
  {
    "id": "seed-u2-47",
    "date": "2026-06-24",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_G36",
    "machineNo": "9",
    "deviceDetail": "HMI",
    "deviceSubCat": "Display",
    "faultCategory": "208-Fault on Display",
    "reason": "208-Fault on Display",
    "actionTaken": "Replace the display and start the machine",
    "shift": "B+C",
    "technician": "M. Mazhar",
    "timeStart": "14:00",
    "timeFinish": "15:15",
    "downtime": "01:15",
    "remarks": ""
  },
  {
    "id": "seed-u2-48",
    "date": "2026-06-24",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_G38",
    "machineNo": "2",
    "deviceDetail": "Relay",
    "deviceSubCat": "K20",
    "faultCategory": "1041-Button was pushed too long",
    "reason": "1041-Button was pushed too long",
    "actionTaken": "After necessary checking start the machine",
    "shift": "B",
    "technician": "M. Mazhar",
    "timeStart": "16:20",
    "timeFinish": "16:30",
    "downtime": "00:10",
    "remarks": ""
  },
  {
    "id": "seed-u2-49",
    "date": "2026-06-24",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "A_11",
    "machineNo": "1",
    "deviceDetail": "Inverter_VFD",
    "deviceSubCat": "",
    "faultCategory": "230-No Connection to Machine",
    "reason": "230-No Connection to Machine",
    "actionTaken": "Reset the inverter and start the machine",
    "shift": "B",
    "technician": "M. Rauf",
    "timeStart": "20:30",
    "timeFinish": "20:50",
    "downtime": "00:20",
    "remarks": ""
  },
  {
    "id": "seed-u2-50",
    "date": "2026-06-24",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_G36",
    "machineNo": "9",
    "deviceDetail": "Inverter_VFD",
    "deviceSubCat": "U1",
    "faultCategory": "Inverter Fault",
    "reason": "Inverter Fault",
    "actionTaken": "Reset the inverter and start the machine",
    "shift": "B",
    "technician": "Afaq",
    "timeStart": "20:40",
    "timeFinish": "20:55",
    "downtime": "00:15",
    "remarks": ""
  },
  {
    "id": "seed-u2-51",
    "date": "2026-06-24",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_G36",
    "machineNo": "7",
    "deviceDetail": "PLC",
    "deviceSubCat": "I/O Module",
    "faultCategory": "Communication Error",
    "reason": "Communication Error",
    "actionTaken": "X20 knot removed occurred, cleaned the module, cold start applied on machine and start the machine",
    "shift": "C",
    "technician": "M. Rauf",
    "timeStart": "03:50",
    "timeFinish": "04:20",
    "downtime": "00:30",
    "remarks": ""
  },
  {
    "id": "seed-u2-52",
    "date": "2026-06-25",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_G36",
    "machineNo": "21",
    "deviceDetail": "HMI",
    "deviceSubCat": "Display",
    "faultCategory": "208-Fault on Display",
    "reason": "208-Fault on Display",
    "actionTaken": "Interchange the display with machine # 7 and get it programmed from fitter and start the machine",
    "shift": "A",
    "technician": "M. Mazhar",
    "timeStart": "08:20",
    "timeFinish": "09:00",
    "downtime": "00:40",
    "remarks": ""
  },
  {
    "id": "seed-u2-53",
    "date": "2026-06-25",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_G36",
    "machineNo": "7",
    "deviceDetail": "HMI",
    "deviceSubCat": "Display",
    "faultCategory": "208-Fault on Display",
    "reason": "208-Fault on Display",
    "actionTaken": "Interchange the display with machine # 21 and get it programmed from fitter and start the machine",
    "shift": "A",
    "technician": "M. Mazhar",
    "timeStart": "08:15",
    "timeFinish": "09:15",
    "downtime": "01:00",
    "remarks": ""
  },
  {
    "id": "seed-u2-54",
    "date": "2026-06-26",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_G36",
    "machineNo": "16",
    "deviceDetail": "Emergency_Switch",
    "deviceSubCat": "S21",
    "faultCategory": "Emergency Switch",
    "reason": "Emergency Switch",
    "actionTaken": "Reset the emergency switch and start the machine",
    "shift": "B",
    "technician": "M. Mazhar",
    "timeStart": "16:00",
    "timeFinish": "16:20",
    "downtime": "00:20",
    "remarks": ""
  },
  {
    "id": "seed-u2-55",
    "date": "2026-06-28",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Drawing_Breaker",
    "machineNo": "9",
    "deviceDetail": "Sensor",
    "deviceSubCat": "B2/B91",
    "faultCategory": "208-Fault on Display",
    "reason": "208-Fault on Display",
    "actionTaken": "Clean and reset the sensors, also check the display and found it faulty, replace the display and get it programmed from fitter and start the machine",
    "shift": "C",
    "technician": "M. Rauf",
    "timeStart": "23:10",
    "timeFinish": "03:30",
    "downtime": "04:20",
    "remarks": ""
  },
  {
    "id": "seed-u2-56",
    "date": "2026-06-29",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Drawing_Finisher",
    "machineNo": "9",
    "deviceDetail": "HMI",
    "deviceSubCat": "Display",
    "faultCategory": "208-Fault on Display",
    "reason": "208-Fault on Display",
    "actionTaken": "Replace the display and get it programmed from fitter and start the machine",
    "shift": "A",
    "technician": "M. Mazhar",
    "timeStart": "15:00",
    "timeFinish": "16:15",
    "downtime": "01:15",
    "remarks": ""
  },
  {
    "id": "seed-u2-57",
    "date": "2026-06-29",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Comber",
    "machineNo": "7",
    "deviceDetail": "Sensor",
    "deviceSubCat": "",
    "faultCategory": "Table Sensor",
    "reason": "Table Sensor",
    "actionTaken": "Re-join the wire and after necessary checking start the machine",
    "shift": "C",
    "technician": "Afaq",
    "timeStart": "03:45",
    "timeFinish": "05:10",
    "downtime": "01:25",
    "remarks": ""
  },
  {
    "id": "seed-u2-58",
    "date": "2026-06-30",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Drawing_Breaker",
    "machineNo": "4",
    "deviceDetail": "PLC",
    "deviceSubCat": "",
    "faultCategory": "PLC Fault",
    "reason": "PLC Fault",
    "actionTaken": "Malfunctioned PLC found, interchage with machine # 5",
    "shift": "A",
    "technician": "M. Mazhar",
    "timeStart": "07:20",
    "timeFinish": "10:30",
    "downtime": "03:10",
    "remarks": ""
  },
  {
    "id": "seed-u2-59",
    "date": "2026-06-30",
    "complaintReference": "Supervisor",
    "ticketNo": "",
    "machine": "Ring_G36",
    "machineNo": "8",
    "deviceDetail": "PLC",
    "deviceSubCat": "I/O Module",
    "faultCategory": "Communication Error",
    "reason": "Communication Error",
    "actionTaken": "X20 knot removed occurred, cleaned the module, cold start applied on machine and start the machine",
    "shift": "B",
    "technician": "M. Rauf",
    "timeStart": "09:00",
    "timeFinish": "09:20",
    "downtime": "00:20",
    "remarks": ""
  }
]

MACHINES_UNIT2 = [
  "A_11",
  "AutoCone_QProEX",
  "Card_C70",
  "Comber",
  "Complete",
  "Drawing_Breaker",
  "Drawing_Finisher",
  "Ring_G36",
  "Ring_G38",
  "Simplex_ElectroJet"
]

SHIFTS_UNIT2 = [
  "A",
  "B",
  "B+C",
  "C"
]

FAULT_CATEGORIES_UNIT2 = [
  "1041-Button was pushed too long",
  "208-Fault on Display",
  "230-No Connection to Machine",
  "471-Drive Fault",
  "A2 Fault",
  "ATL No Communication Fault",
  "Can Bus Communication",
  "Circuit Breaker Trip",
  "Coil",
  "Communication Error",
  "Emergency Relay",
  "Emergency Switch",
  "G90 Error",
  "Inverter Fault",
  "Jack Loosing",
  "Loose Connections",
  "Motor",
  "Motor Bearing",
  "Over Heat + Over Temperature",
  "Over Load",
  "Over Voltage",
  "PLC Fault",
  "Ring Rail Position Out",
  "Sensor Jack Loosening",
  "Shut Down",
  "Table Sensor",
  "Wire Breakage"
]

TECHNICIANS_UNIT2 = [
  "Afaq",
  "M. Mazhar",
  "M. Rauf",
  "Makki Khan"
]

NOTIFICATION_TYPES_UNIT2 = [
  "Breakdown",
  "Preventive Maintenance",
  "Electrical",
  "Mechanical",
  "Emergency"
]

COMPLAINT_REFERENCES_UNIT2 = [
  "Power House",
  "Supervisor"
]

DEVICE_DETAILS_UNIT2 = [
  "CBF",
  "Circuit_Breaker",
  "Drive",
  "Emergency_Switch",
  "HMI",
  "Inverter_VFD",
  "Motor",
  "PLC",
  "Relay",
  "Ring_Rail",
  "Sensor"
]

DEVICE_SUB_CATEGORIES_UNIT2 = [
  "A2",
  "A8",
  "B2",
  "B2/B91",
  "B3",
  "B312",
  "B7",
  "Display",
  "G90",
  "I/O Module",
  "K20",
  "M13",
  "M2",
  "M82",
  "M90",
  "Q6",
  "S20",
  "S21",
  "Slave 5",
  "U1",
  "U101",
  "U11",
  "U12",
  "U60"
]
